exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: "Reverse the auditory processing pathway: Coarse-to-fine audio reconstruction from human brain activity"
#description: Primer is a Jekyll theme for GitHub Pages

baseurl: "/c2f-ldm"
url: "https://neurofusex.github.io"
